
services:
# Nginx - A "Porta de Entrada" do teu sistema
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: always

  # Banco de Dados (Exemplo com PostgreSQL)
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: lawfirm_db
      POSTGRES_USER: user_admin      # O nome que você escolher
      POSTGRES_PASSWORD: password123 # A senha que você escolher
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Isso cria uma pasta no seu PC com os dados
    ports:
      - "5432:5432"
    restart: always  # Adicione esta linha

  # PgAdmin para gerenciar o PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    profiles:
      - debug  # O container só sobe se você chamar o profile 'debug'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    depends_on:
      - db
    
  # Backend Spring Boot
  backend:
    build: ./LawFirmAPI
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/lawfirm_db
      - DB_USER=user_admin           # Deve ser igual ao POSTGRES_USER
      - DB_PASSWORD=password123      # Deve ser igual ao POSTGRES_PASSWORD
      - EMAIL_PASSWORD=Teste123.@ # Pega do seu .env local
      - EMAIL_USER=testeddd@sapo.pt       # Pega do seu .env local
    depends_on:
      - db
    restart: always  # Adicione esta linha

  # Frontend React
  frontend:
    build: 
      context: ./LawFirmWebApp
      dockerfile: Dockerfile
    platform: linux/amd64
    # ports:
    #   - "5173:5173"
    volumes:
      - ./LawFirmWebApp:/app
      - /app/node_modules  # Protege os módulos instalados no build
    environment:
      - VITE_SERVER_API_URL=http://wagneradvocacia.local/api  # Substitua pelo seu IP local
    depends_on:
      - backend
    restart: always
    
volumes:
  postgres_data: